"""Second

Revision ID: 726fed431f90
Revises: ec8a7d54d740
Create Date: 2023-02-20 17:39:31.162249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726fed431f90'
down_revision = 'ec8a7d54d740'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
